versions:
  version: dev-0.0.7
server:
  port: 9098

spring:
  redis:
    database: 0
    host: localhost
    port: 9736
    password: 123456
    jedis:
      pool:
        max-idle: 10 #连接池最大连接数（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8 # 连接池中的最大空闲连接
    timeout: 5000ms # 连接超时时间（毫秒）
  datasource:
    url: jdbc:postgresql://localhost:5432/mishang_business_db
    username: mishang_business_user
    password: mishang_business_pass
    driverClassName: org.postgresql.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: select 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    show-sql: true